USE_SIMULATION = False
SAMPLE_INTERVAL_S = 0.1
LOOP_DELAY_S = 0.01

# Motion configuration.
SCREW_LEAD_MM_PER_REV = 8.0
STEPPER_FULL_STEPS_PER_REV = 200
STEPPER_MICROSTEPS = 8
ENCODER_COUNTS_PER_REV = 4096
ENCODER_SLIP_TOLERANCE_MM = 0.25
HOME_DIRECTION = -1
LEFT_HOME_DIRECTION = 1
RIGHT_HOME_DIRECTION = -1

# ERB motor sockets from the provided Klipper mapping.
MOTOR_A_STEP_PIN = "gpio10"
MOTOR_A_DIR_PIN = "gpio9"
MOTOR_A_ENABLE_PIN = "gpio8"
MOTOR_A_UART_PIN = "gpio20"
MOTOR_A_DIRECTION_INVERTED = False

MOTOR_B_STEP_PIN = "gpio16"
MOTOR_B_DIR_PIN = "gpio15"
MOTOR_B_ENABLE_PIN = "gpio14"
MOTOR_B_UART_PIN = "gpio17"
MOTOR_B_DIRECTION_INVERTED = True

# Home switches.
LEFT_HOME_SWITCH_PIN = "gpio22"
RIGHT_HOME_SWITCH_PIN = "gpio23"
HOME_SWITCH_ACTIVE_LOW = True
HOME_SWITCH_PULL_UP = True
LEFT_HOME_SWITCH_ACTIVE_LOW = False
LEFT_HOME_SWITCH_PULL_UP = False
RIGHT_HOME_SWITCH_ACTIVE_LOW = True
RIGHT_HOME_SWITCH_PULL_UP = True

# Spare GPIO defaults for sensors. Adjust these to your actual wiring.
LEFT_ENCODER_SCL_PIN = "gpio29"
LEFT_ENCODER_SDA_PIN = "gpio28"
RIGHT_ENCODER_SCL_PIN = "gpio27"
RIGHT_ENCODER_SDA_PIN = "gpio26"
LEFT_ENCODER_INVERTED = True
RIGHT_ENCODER_INVERTED = False
HX711_DATA_PIN = "gpio24"
HX711_CLOCK_PIN = "gpio25"

# TMC2209 write-only UART tuning.
TMC_UART_BAUDRATE = 9600
TMC_INTERPOLATE = True
TMC_SENSE_RESISTOR_OHMS = 0.110
MOTOR_A_RUN_CURRENT_A = 0.5
MOTOR_A_HOLD_CURRENT_A = 0.10
MOTOR_B_RUN_CURRENT_A = 0.5
MOTOR_B_HOLD_CURRENT_A = 0.10

# Homing.
HOME_FAST_SPEED_MM_PER_MIN = 120.0
HOME_SLOW_SPEED_MM_PER_MIN = 20.0
HOME_BACKOFF_MM = 2.0
HOME_TIMEOUT_S = 20.0
HOME_SWITCH_MODE = "single"
SINGLE_HOME_SWITCH_AXIS = "left"

# HX711 calibration. Replace counts-per-newton with your measured calibration.
HX711_COUNTS_PER_NEWTON = 1000.0
HX711_AVERAGE_SAMPLES = 5
HX711_TARE_SAMPLES = 8

# Step pulse width for GPIO stepping.
STEP_PULSE_S = 0.00001
